# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smooth"
primary_region = "iad"
swap_size_mb = 2048

[processes]
  app = "foreman start --procfile=Procfile.fly"

[[mounts]]
  source = "smooth_volume"
  destination = "/data"
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "100GB"

[http_service]
  processes = ['app']
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  processes = ['app']
  internal_port = 2222
  protocol = "tcp"
  [[services.ports]]
    port = 2222

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
