# Source - Receive via Vector's native protocol (no TLS - Traefik handles it)
[sources.vector_receiver]
type = "vector"
address = "0.0.0.0:9001"  # Listen inside container, Traefik proxies to this
version = "2"
connection_limit = 200  # Support up to 200 concurrent connections
keepalive.enabled = true
keepalive.time_secs = 60
# No TLS needed - Traefik terminates TLS and forwards plain TCP to Vector
# Authentication using Rails master key
auth.strategy = "bearer"
auth.token = "${RAILS_MASTER_KEY}"

# Transform - Extract date from timestamp
[transforms.add_date]
type = "remap"
inputs = ["vector_receiver"]
source = '''
.date = format_timestamp!(.["@timestamp"], "%Y-%m-%d")
'''

# Sink - Write to daily log file
[sinks.daily_logs]
type = "file"
inputs = ["add_date"]
path = "/logs/showcase/{{ date }}.log"  # Container path
encoding.codec = "json"
compression = "gzip"

# Optional: Separate error logs
[sinks.errors]
type = "file"
inputs = ["add_date"]
path = "/logs/showcase/errors-{{ date }}.log"
encoding.codec = "json"
condition = '.stream == "stderr" || .level == "error" || .level == "ERROR"'