# Source - Receive via Vector's native protocol v2 (gRPC)
[sources.vector_receiver]
type = "vector"
address = "0.0.0.0:9000"  # Listen directly on port 9000
version = "2"

# Transform - Extract date from timestamp
[transforms.add_date]
type = "remap"
inputs = ["vector_receiver"]
source = '''
.date = format_timestamp!(."@timestamp", "%Y-%m-%d")
'''

# Sink - Write to daily log file
[sinks.daily_logs]
type = "file"
inputs = ["add_date"]
path = "/logs/showcase/{{ date }}.log"  # Container path
encoding.codec = "json"
compression = "gzip"

# Optional: Filter for errors
[transforms.filter_errors]
type = "filter"
inputs = ["add_date"]
condition = '.stream == "stderr" || .level == "error" || .level == "ERROR"'

# Separate error logs
[sinks.errors]
type = "file"
inputs = ["filter_errors"]
path = "/logs/showcase/errors-{{ date }}.log"
encoding.codec = "json"